CREATE TABLE IF NOT EXISTS USER (
  uid BIGINT NOT NULL AUTO_INCREMENT,
  uname VARCHAR(20),
  balance DOUBLE,
  frozen BOOL DEFAULT FALSE,
  PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS PACK (
  pid BIGINT NOT NULL AUTO_INCREMENT,
  pname VARCHAR(50),
  fee DOUBLE NOT NULL,
  PRIMARY KEY (pid)
);

CREATE TABLE IF NOT EXISTS PACK_OFFER (
  oid BIGINT NOT NULL AUTO_INCREMENT,
  pid BIGINT NOT NULL,
  offerType INT NOT NULL,
  quantity DOUBLE DEFAULT 0,
  PRIMARY KEY (oid),
  FOREIGN KEY (oid) REFERENCES PACK(pid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USER_ORDER (
  orderId BIGINT NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  pid BIGINT NOT NULL,
  month DATE NOT NULL,
  renewing BOOL DEFAULT TRUE,
  FOREIGN KEY (uid) REFERENCES USER(uid) ON DELETE CASCADE,
  FOREIGN KEY (pid) REFERENCES PACK(pid),
  PRIMARY KEY (orderId)
);

CREATE TABLE IF NOT EXISTS CALL_USAGE (
  callId BIGINT NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  finishDatetime DATETIME NOT NULL,
  callTime DOUBLE DEFAULT 0,
  PRIMARY KEY (callId),
  FOREIGN KEY (uid) REFERENCES USER(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MES_USAGE (
  mesId BIGINT NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  finishDatetime DATETIME NOT NULL,
  PRIMARY KEY (mesId),
  FOREIGN KEY (uid) REFERENCES USER(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOCAL_TRAFFIC (
  ltId BIGINT NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  finishDatetime DATETIME NOT NULL,
  traffic DOUBLE DEFAULT 0,
  PRIMARY KEY (ltId),
  FOREIGN KEY (uid) REFERENCES USER(uid) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DOMESTIC_TRAFFIC (
  dtId BIGINT NOT NULL AUTO_INCREMENT,
  uid BIGINT NOT NULL,
  finishDatetime DATETIME NOT NULL,
  traffic DOUBLE DEFAULT 0,
  PRIMARY KEY (dtId),
  FOREIGN KEY (uid) REFERENCES USER(uid) ON DELETE CASCADE
);